name: Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [0.4.0-beta, main]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { rust: nightly, os: macos-latest }
          - { rust: nightly, os: ubuntu-latest }
          - { rust: nightly, os: windows-latest }
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - name: Clippy
        run: cargo clippy --all-features --verbose
      - name: Lint docs
        run: cargo doc --all-features --verbose
      - name: Test
        run: cargo test --all-features --verbose
