name: Create release

on:
  push:
    tags:
      - "v*.*.*(-.*)?"

jobs:
  set-toolchain:
    name: Set TOOLCHAIN
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag matches pattern
        id: tag_check
        run: |
          if [[ ${{ github.ref }} ~= grep -q -E '.*v[0-9]+\.[0-9]+\.[0-9]+$' ]]; then
            echo "IS_STABLE_VERSION=true" >> $GITHUB_OUTPUT
          else
            echo "IS_STABLE_VERSION=false" >> $GITHUB_OUTPUT
          fi
      - name: Set TOOLCHAIN to stable if stable tag
        if: steps.tag_check.outputs.IS_STABLE_VERSION
        run: echo "TOOLCHAIN=stable" >> $GITHUB_ENV
      - name: Set TOOLCHAIN to nightly if unstable tag
        if: steps.tag_check.outputs.IS_STABLE_VERSION != true
        run: echo "TOOLCHAIN=stable" >> $GITHUB_ENV

  release:
    name: Create new release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          makeLatest: true
      - name: Update changelog
        uses: dropseed/changerelease@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: CHANGELOG.md

  publish:
    name: Publish
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.TOOLCHAIN }}
      - name: Cargo login
        run: cargo login ${{ secrets.CRATES_IO_API_TOKEN }}
      - name: Cargo dry run
        run: cargo publish --dry-run
      - name: Cargo publish
        run: cargo publish
