name: publish-crate

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  publish:
    name: Publish crate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo publish --dry-run
      - run: cargo login ${CRATES_TOKEN}
      - run: cargo publish
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
