name: Create release

on:
  push:
    tags:
      - 'v*'

env:
  TOOLCHAIN: stable

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.TOOLCHAIN }}
      - name: Test
        run: cargo test --all-features --verbose

  create-release:
    name: Create new release
    needs: test
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          makeLatest: true
      - name: Update changelog
        uses: dropseed/changerelease@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: CHANGELOG.md