name: rust

on:
  pull_request:
    branches: [dev, main]
  push:
    branches: [dev, main]

jobs:
  clippy:
    name: Clippy
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - run: cargo clippy --all-features --verbose

  doc:
    name: Docs
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo doc --all-features --verbose

  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { rust: 1.56.0, os: windows-2019 }
          - { rust: 1.56.0, os: macos-11 }
          - { rust: 1.56.0, os: ubuntu-latest }
          - { rust: stable, os: windows-2019 }
          - { rust: stable-i686-msvc, os: windows-2019 }
          - { rust: stable, os: macos-latest }
          - { rust: stable, os: ubuntu-latest }
          - { rust: beta, os: windows-latest }
          - { rust: nightly, os: windows-latest }
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --all-features --verbose
